"""
PDF report generation with fpdf2.
Takes a scan document (dict from MongoDB) and returns PDF bytes.
"""

from __future__ import annotations

import base64
import io
import tempfile
import os
from datetime import datetime

from fpdf import FPDF


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(37, 99, 235)   # blue-600
        self.cell(0, 10, "AI Doctor", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 116, 139)  # slate-500
        self.cell(0, 6, "Multimodal Medical AI Assistant", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_draw_color(226, 232, 240)  # slate-200
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)  # slate-400
        self.cell(0, 5,
            "EDUCATIONAL USE ONLY  - This report is not a substitute for professional medical advice.",
            align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, f"Page {self.page_no()}", align="C")


def generate_report(scan: dict) -> bytes:
    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    # --- Disclaimer banner ---
    pdf.set_fill_color(254, 243, 199)    # yellow-100
    pdf.set_draw_color(253, 230, 138)    # yellow-200
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(146, 64, 14)      # yellow-800
    pdf.cell(0, 8,
        "  Educational use only  - Not a substitute for professional medical advice",
        border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # --- Report metadata ---
    created_at = scan.get("createdAt") or scan.get("created_at") or ""
    if created_at:
        try:
            if isinstance(created_at, str):
                dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            else:
                dt = created_at
            date_str = dt.strftime("%d %B %Y, %H:%M UTC")
        except Exception:
            date_str = str(created_at)
    else:
        date_str = datetime.utcnow().strftime("%d %B %Y, %H:%M UTC")

    _section_header(pdf, "Report Details")
    _row(pdf, "Date", date_str)
    _row(pdf, "Report ID", str(scan.get("_id", "N/A")))
    _row(pdf, "Analysis type", "Chest X-ray Classification" if scan.get("kind") == "xray" else "Symptom Analysis")
    pdf.ln(4)

    kind = scan.get("kind")

    if kind == "xray":
        _build_xray_section(pdf, scan)
    else:
        _build_symptom_section(pdf, scan)

    # --- Disclaimer page ---
    pdf.add_page()
    _section_header(pdf, "Important Disclaimer")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    disclaimer = (
        "This report was generated by an AI-based screening tool for educational and "
        "informational purposes only. The AI model used in this analysis (ResNet-50 fine-tuned "
        "on chest X-ray data) has not been validated for clinical use and should not be used "
        "as a substitute for professional medical diagnosis, advice, or treatment.\n\n"
        "Always seek the advice of your physician or other qualified health provider with any "
        "questions you may have regarding a medical condition. Never disregard professional "
        "medical advice or delay in seeking it because of information provided by this tool.\n\n"
        "If you think you may have a medical emergency, call your doctor, go to the nearest "
        "emergency room, or call emergency services immediately."
    )
    pdf.multi_cell(0, 6, disclaimer)

    return bytes(pdf.output())


def _build_xray_section(pdf: FPDF, scan: dict):
    _section_header(pdf, "X-ray Analysis Result")

    label = scan.get("label", "Unknown")
    confidence = scan.get("confidence", 0)
    pct = round(confidence * 100, 1)

    _row(pdf, "Detected condition", label)
    _row(pdf, "Confidence score", f"{pct}%")
    _row(pdf, "Model", scan.get("model", "resnet50-keras-v1"))

    classes = scan.get("classes") or scan.get("classes_", [])
    if classes:
        _row(pdf, "Classes evaluated", ", ".join(classes))

    pdf.ln(4)

    # Confidence bar
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, "Confidence level:", new_x="LMARGIN", new_y="NEXT")
    bar_w = 160
    filled = int(bar_w * confidence)
    pdf.set_fill_color(226, 232, 240)
    pdf.rect(15, pdf.get_y(), bar_w, 6, style="F")
    color = (37, 99, 235) if pct >= 75 else (245, 158, 11) if pct >= 50 else (148, 163, 184)
    pdf.set_fill_color(*color)
    if filled > 0:
        pdf.rect(15, pdf.get_y(), filled, 6, style="F")
    pdf.ln(10)

    # Gemini explanation
    explanation = scan.get("geminiExplanation") or scan.get("gemini_explanation")
    if explanation:
        _section_header(pdf, "AI Explanation")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(0, 6, explanation)
        pdf.ln(2)

    # Heatmap image
    heatmap_b64 = scan.get("heatmapBase64") or scan.get("heatmap_base64")
    if heatmap_b64:
        _section_header(pdf, "Grad-CAM Heatmap")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 5,
            "Highlighted regions show which areas of the X-ray influenced the AI prediction.",
            new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        try:
            img_data = base64.b64decode(heatmap_b64)
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                tmp.write(img_data)
                tmp_path = tmp.name
            pdf.image(tmp_path, x=40, w=120)
            os.unlink(tmp_path)
        except Exception as e:
            pdf.set_text_color(239, 68, 68)
            pdf.cell(0, 5, f"Heatmap could not be embedded: {e}")
        pdf.ln(4)


def _build_symptom_section(pdf: FPDF, scan: dict):
    _section_header(pdf, "Symptom Analysis")

    input_text = (scan.get("input") or {}).get("text", "N/A")
    _row(pdf, "Reported symptoms", input_text)

    entities = scan.get("entities") or []
    if entities:
        _row(pdf, "Detected medical entities", ", ".join(entities))

    conditions = scan.get("possibleConditions") or scan.get("possible_conditions") or []
    if conditions:
        _row(pdf, "Possible conditions", ", ".join(conditions))

    emergency = scan.get("emergency") or {}
    if emergency.get("isEmergency") or emergency.get("is_emergency"):
        pdf.ln(2)
        pdf.set_fill_color(254, 226, 226)
        pdf.set_draw_color(252, 165, 165)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(153, 27, 27)
        pdf.cell(0, 8, "  EMERGENCY: Critical symptom detected  - seek immediate medical attention",
            border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    gemini = scan.get("geminiResponse") or scan.get("gemini_response")
    if gemini:
        pdf.ln(4)
        _section_header(pdf, "AI Response")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(0, 6, gemini)


def _section_header(pdf: FPDF, title: str):
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(219, 234, 254)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)


def _row(pdf: FPDF, key: str, value: str):
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(50, 6, key + ":", new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.multi_cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")
